Iana/precompiling
UseKeyp/usekeyp-js-sdk pull request #21
Opened 2023-04-18 18:12 UTC by alekseevaiana

## What I did
- installed additional Babel dependencies
- created babel.config.js file
- changed build command in package.json to build lib folder with compiled js files
- updated documentation

## Comments
- tested it with Github Actions
- might need to add lib into .gitignore and add build command into github actions

2023-04-19 22:08 UTC, pi0neerpat requested changes
Nice work so far. I couldn't get the styles to work in my create-react-app, but there were not other errors and the installation process already looks so much better!

![image](https://user-images.githubusercontent.com/35622595/233210408-ce0b4446-276e-4ab9-9f1b-1e556a7a4a2f.png)

2023-04-19 22:08 UTC, pi0neerpat commented on packages/ui-library/README.md
> +    `yarn add -D tailwindcss@latest`
Should this be installed as a developer or normal dependency?

2023-04-19 22:08 UTC, pi0neerpat commented on packages/ui-library/README.md
> +    2.1 Install the latest version of Tailwind.
I think including a minimum version number support here is important. eg. if the user already has tailwind, they might not realize they must update.

2023-04-19 22:08 UTC, pi0neerpat commented on packages/ui-library/README.md
> +    2.4 Start the Tailwind CLI build process. You can add this command to your build process.
I think we need to show some examples of how to add this to package.json for React apps and NextJS apps.  Please show an example package.json for each where the build script has this added as necessary.

2023-04-19 22:08 UTC, pi0neerpat commented on packages/ui-library/lib/components/MoreAccordion/MoreAccordion.js
I think we should gitignore `packages/ui-library/lib/components` or the entire `/lib` folder since these are all built files. A package is always built prior to publishing, so we don't need to version control these.

2023-04-19 22:08 UTC, pi0neerpat commented on packages/ui-library/src/components/Button/Button.jsx
> +import React from "react";
Nice! Sometimes the smallest things make such a big difference

2023-04-19 22:08 UTC, pi0neerpat commented on packages/ui-library/package.json
> +    "build": "styleguidist build --config styleguide.config.cjs && babel --config-file ./babel.config.js src -d lib && rsync -r --exclude=*.js --exclude=*.jsx src/ lib/",
Can you rename "b" to something that explains its function and differentiation from "build"

2023-04-19 22:47 UTC, alekseevaiana commented on packages/ui-library/README.md
> +    `yarn add -D tailwindcss@latest`
It is installed in my devDependencies.

2023-04-19 22:49 UTC, alekseevaiana commented on packages/ui-library/README.md
> +    2.1 Install the latest version of Tailwind.
Actually, I think that it has to work with older versions. You just have to include a plugin. I will try

2023-04-19 22:51 UTC, alekseevaiana commented on packages/ui-library/README.md
> +    `yarn add -D tailwindcss@latest`
How is your tailwind.config.js file look like? 
Also, I think you should include these lines in index.css. Will add it to the documentation.
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

2023-04-19 22:52 UTC, alekseevaiana commented on packages/ui-library/lib/components/MoreAccordion/MoreAccordion.js
ok!

2023-04-19 22:55 UTC, alekseevaiana commented on packages/ui-library/package.json
> +    "build": "styleguidist build --config styleguide.config.cjs && babel --config-file ./babel.config.js src -d lib && rsync -r --exclude=*.js --exclude=*.jsx src/ lib/",
I will remove it because I already included it in the build. Is it ok?

2023-04-19 23:35 UTC, pi0neerpat commented on packages/ui-library/package.json
> +    "build": "styleguidist build --config styleguide.config.cjs && babel --config-file ./babel.config.js src -d lib && rsync -r --exclude=*.js --exclude=*.jsx src/ lib/",
Sounds good

2023-04-19 23:38 UTC, pi0neerpat commented on packages/ui-library/README.md
> +    `yarn add -D tailwindcss@latest`
Much better now 
![image](https://user-images.githubusercontent.com/35622595/233221996-d397d148-4c62-460f-8025-2dc86cea1110.png)

2023-04-19 23:41 UTC, pi0neerpat commented on packages/ui-library/README.md
> +    `yarn add -D tailwindcss@latest`
I added my app in the /examples folder on the dev branch

2023-04-19 23:46 UTC, alekseevaiana commented on packages/ui-library/README.md
> +    `yarn add -D tailwindcss@latest`
I think I should add explicit color for the LoginPortal... And width.

2023-04-19 23:50 UTC, pi0neerpat commented on packages/ui-library/README.md
> +    `yarn add -D tailwindcss@latest`
No need, I added this to another issue :)

2023-04-20 18:34 UTC, alekseevaiana commented on packages/ui-library/README.md
> +    2.1 Install the latest version of Tailwind.
Great, I found a bug: if I use the latest version syntax (ESM), the older version (I tried which I found in frontend-components: ^3.2.1) can't transform it. But I can improve to the older syntax and it still works.

<img width="1393" alt="Screenshot 2023-04-20 at 10 51 50 AM" src="https://user-images.githubusercontent.com/36742189/233448262-6a130b06-9d95-4a00-a1f7-86e22c03f790.png">

2023-04-20 18:37 UTC, alekseevaiana commented on packages/ui-library/lib/components/MoreAccordion/MoreAccordion.js
I put lib in .gitignore, but now the package compiles without lib folder at all...

2023-04-20 20:26 UTC, alekseevaiana commented on packages/ui-library/README.md
> +    2.4 Start the Tailwind CLI build process. You can add this command to your build process.
Added

2023-04-20 20:28 UTC, alekseevaiana commented
@pi0neerpat could you take a look at why the lib folder is not compiling? Is it because Github Actions? I tried to understand, but can't find where it is running.

2023-04-21 03:44 UTC, alekseevaiana commented
@pi0neerpat It publishes now! Thanks for your help! :)

2023-04-21 19:29 UTC, pi0neerpat requested changes

2023-04-21 19:29 UTC, pi0neerpat commented on packages/ui-library/package.json
> +    "pre-publish": "babel --config-file ./babel.config.js src -d lib ",
This doesn't generate the necessary tailwind files does it?

2023-04-21 19:29 UTC, pi0neerpat commented on packages/ui-library/package.json
> +    "src"
Why is src included? I don't think it should be since the package used the /lib folder for all code, and everything is being copied to that folder

2023-04-21 20:11 UTC, alekseevaiana commented on packages/ui-library/package.json
> +    "src"
I thought we had to use it here, but you are right, it works the same if I use lib. Improved. Including docs.

<img width="678" alt="Screenshot 2023-04-21 at 12 45 23 PM" src="https://user-images.githubusercontent.com/36742189/233723582-9e60835a-33c3-44e0-a4c8-9c0ff85a4414.png">

2023-04-21 20:16 UTC, alekseevaiana commented on packages/ui-library/package.json
> +    "pre-publish": "babel --config-file ./babel.config.js src -d lib ",
We don't need it at this stage, I think. We pre-publish it only to generate `lib` folder with compiled js files.

2023-04-21 22:09 UTC, pi0neerpat approved these changes
Excellent work!

2023-04-21 22:14 UTC, merged