[ui] UserAccount component
UseKeyp/usekeyp-js-sdk pull request #32
Opened 2023-05-18 19:01 UTC by alekseevaiana

Closes #20 

## Bugs:
When use multiple UserAccounts on a page, Tooltip is very buggy: if click on "copy", there is second tooltip appears, or not appears at all. But if there is only one UserAccount everything works good. 
Since we use only one UserAccount on page, I think we can publish it.
**Example of buggy Tooltip:**

<img width="611" alt="Screenshot 2023-05-18 at 11 08 49 AM" src="https://github.com/UseKeyp/usekeyp-js-sdk/assets/36742189/2c5e978d-57b6-4982-b829-62ee217efbb7">

**Example of working Tooltip:**

https://github.com/UseKeyp/usekeyp-js-sdk/assets/36742189/95213fc5-5f85-4b34-9ea0-20a6de9c758e

2023-05-18 23:49 UTC, pi0neerpat requested changes
Looks good just a few changes

- Can you add Spotify, which was recently added 
- Some of the examples don't have the provider icon. Lets make them all show the correct icon.

Also, nice job working with Sascha on the QA. Love to see the coordination!

2023-05-18 23:49 UTC, pi0neerpat commented on packages/ui-kit/src/components/UserAccount/helpers.jsx
> +    microsoft: { name: "microsoft", marginTop: "mt-0.5" },
- I noticed the naming convention here has changed. Can we keep it consistent?
- Also, can you please move `trimAddress` to a new file src/helpers.js. It is likely to be used in multiple different components

2023-05-22 22:27 UTC, jahabeebs requested changes
good job! I made a couple comments for you to check out. Also I see that you were dealing with duplicate tooltips with UserAccount. This is because tooltip IDs need to be unique to prevent duplicate rendering on the page. As you suggested this won't affect us because we only use one UserAccount per page but it's something to keep in mind. Here are their docs for more info: https://www.npmjs.com/package/react-tooltip. When you make the corrections feel free to request review again

2023-05-22 22:27 UTC, jahabeebs commented on packages/ui-kit/plugin.js
> +            twitch: "#9146FF",
nice I like that all the brand colors are here

2023-05-22 22:27 UTC, jahabeebs commented on packages/ui-kit/src/components/LoginButton/LoginButton.jsx
> +    provider !== "REDDIT" &&
getTextColor and getLabelFromProvider are fine for now though I think in the future we'll probably make this into a switch statement (like switch (provider)) or else we're going to have a lot of else if statements

2023-05-22 22:27 UTC, jahabeebs commented on packages/ui-kit/src/components/LoginButton/LoginButton.jsx
> +                width="24"
why are the heights and widths 30 when loading is true and 24 when false?

2023-05-22 22:27 UTC, jahabeebs commented on packages/ui-kit/src/components/UserAccount/UserAccount.md
> +  accessToken: "SUcVls92PKQlHuYIbar2xiOWjOq9XWI4_578kMzbsr1",
Let's take out accessToken from these examples because they're not needed for the UserAccount examples and technically these are secrets so we should protect these

2023-05-23 00:29 UTC, alekseevaiana commented on packages/ui-kit/src/components/LoginButton/LoginButton.jsx
> +                width="24"
They are different icons on squire buttons. When loading, I don't need brand icon, instead, I show loading icon that has different size. Icons size I took from the design and loading I just used like it was on a usual LoginButton.

2023-05-23 00:55 UTC, alekseevaiana commented
> This is because tooltip IDs need to be unique to prevent duplicate rendering on the page. As you suggested this won't affect us because we only use one UserAccount per page but it's something to keep in mind.

This is it. Thanks!!! I changed user addresses examples to make unique ids on this page. I think it is great that now it works without bugs. Let me know if this solution doesn't work for us.

2023-05-23 17:30 UTC, jahabeebs approved these changes
👍🏻

2023-05-23 17:53 UTC, merged